package AuctionApp;


/**
* AuctionApp/AuctionServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Thursday, February 23, 2017 7:00:49 PM CST
*/

public interface AuctionServerOperations 
{
  String viewAuctionStatus (String id);
  String bid (String id, float amount);
  String viewBidStatus (String id);
  String offerItem (String id, AuctionApp.Item item);
  String viewHighBidder (String id);
  String sell (String id);
} // interface AuctionServerOperations
