package AuctionApp;


/**
* AuctionApp/AuctionServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Thursday, February 23, 2017 7:00:48 PM CST
*/

public abstract class AuctionServerPOA extends org.omg.PortableServer.Servant
 implements AuctionApp.AuctionServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("viewAuctionStatus", new java.lang.Integer (0));
    _methods.put ("bid", new java.lang.Integer (1));
    _methods.put ("viewBidStatus", new java.lang.Integer (2));
    _methods.put ("offerItem", new java.lang.Integer (3));
    _methods.put ("viewHighBidder", new java.lang.Integer (4));
    _methods.put ("sell", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AuctionApp/AuctionServer/viewAuctionStatus
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.viewAuctionStatus (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // AuctionApp/AuctionServer/bid
       {
         String id = in.read_string ();
         float amount = in.read_float ();
         String $result = null;
         $result = this.bid (id, amount);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // AuctionApp/AuctionServer/viewBidStatus
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.viewBidStatus (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // AuctionApp/AuctionServer/offerItem
       {
         String id = in.read_string ();
         AuctionApp.Item item = AuctionApp.ItemHelper.read (in);
         String $result = null;
         $result = this.offerItem (id, item);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // AuctionApp/AuctionServer/viewHighBidder
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.viewHighBidder (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // AuctionApp/AuctionServer/sell
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.sell (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AuctionApp/AuctionServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AuctionServer _this() 
  {
    return AuctionServerHelper.narrow(
    super._this_object());
  }

  public AuctionServer _this(org.omg.CORBA.ORB orb) 
  {
    return AuctionServerHelper.narrow(
    super._this_object(orb));
  }


} // class AuctionServerPOA
