package com.abc.AuctionApp;

/**
* com/abc/AuctionApp/AuctionServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Thursday, February 23, 2017 6:53:15 PM CST
*/

public final class AuctionServerHolder implements org.omg.CORBA.portable.Streamable
{
  public com.abc.AuctionApp.AuctionServer value = null;

  public AuctionServerHolder ()
  {
  }

  public AuctionServerHolder (com.abc.AuctionApp.AuctionServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.abc.AuctionApp.AuctionServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.abc.AuctionApp.AuctionServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.abc.AuctionApp.AuctionServerHelper.type ();
  }

}
