package com.abc.AuctionApp;


/**
* com/abc/AuctionApp/AuctionServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Thursday, February 23, 2017 6:53:15 PM CST
*/

public interface AuctionServer extends AuctionServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuctionServer
