package com.abc.AuctionApp;


/**
* com/abc/AuctionApp/AuctionServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Thursday, February 23, 2017 6:53:15 PM CST
*/

abstract public class AuctionServerHelper
{
  private static String  _id = "IDL:AuctionApp/AuctionServer:1.0";

  public static void insert (org.omg.CORBA.Any a, com.abc.AuctionApp.AuctionServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.abc.AuctionApp.AuctionServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.abc.AuctionApp.AuctionServerHelper.id (), "AuctionServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.abc.AuctionApp.AuctionServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AuctionServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.abc.AuctionApp.AuctionServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.abc.AuctionApp.AuctionServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.abc.AuctionApp.AuctionServer)
      return (com.abc.AuctionApp.AuctionServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.abc.AuctionApp._AuctionServerStub stub = new com.abc.AuctionApp._AuctionServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.abc.AuctionApp.AuctionServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.abc.AuctionApp.AuctionServer)
      return (com.abc.AuctionApp.AuctionServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.abc.AuctionApp._AuctionServerStub stub = new com.abc.AuctionApp._AuctionServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
