package com.abc.AuctionApp;

/**
* com/abc/AuctionApp/ItemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Thursday, February 23, 2017 6:53:15 PM CST
*/

public final class ItemHolder implements org.omg.CORBA.portable.Streamable
{
  public com.abc.AuctionApp.Item value = null;

  public ItemHolder ()
  {
  }

  public ItemHolder (com.abc.AuctionApp.Item initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.abc.AuctionApp.ItemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.abc.AuctionApp.ItemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.abc.AuctionApp.ItemHelper.type ();
  }

}
