package com.abc.AuctionApp;


/**
* com/abc/AuctionApp/Item.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Thursday, February 23, 2017 6:53:15 PM CST
*/

public final class Item implements org.omg.CORBA.portable.IDLEntity
{
  public String description = null;
  public float initialPrice = (float)0;

  public Item ()
  {
  } // ctor

  public Item (String _description, float _initialPrice)
  {
    description = _description;
    initialPrice = _initialPrice;
  } // ctor

} // class Item
